### ISSUE TITLE
Crash on startup - Fabric - 1.19.3

### ISSUE THREAD

**Issue by SleepyCatten** [TrattMods/LiterallyChunkLoader#16]
No crash report was created.

Latest log - https://gist.github.com/SleepyCatten/e0263973e56ae477b61093a33b97aa30

**Comment by qtCherry** [comment]
I have the same problem. The game crashes when trying to launch fabric-loader 1.19.3 with this mod installed.
➤ 
[crash-2023-01-08_00.42.58-client.txt](https://github.com/TrattMods/LiterallyChunkLoader/files/10367403/crash-2023-01-08_00.42.58-client.txt)

**Comment by tratteo** [comment]
The crash is related to different ways of registering blocks adpoted in Minecraft **1.19.3**: [source](https://fabricmc.net/wiki/tutorial:blocks#:~:text=If%20you%27re%20using%20version%201.19.2%20or%20below%2C%20please%20replace%20Registries.BLOCK%20with%20Registry.BLOCK%E3%80%82).
I will upload a new version specifically for _1.19.3_

**Comment by tratteo** [comment]
Fixed on new version 1.19.3-2.0.5 on Curseforge.
Will be available upon approval at this link: https://www.curseforge.com/minecraft/mc-mods/literally-chunk-loader/files/4356672
